### Variables
@baseUrl = http://localhost:8080/api/gyms

### 1. Power House
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Power House",
  "address": "ul. Puławska 1, 00-001 Warszawa",
  "phoneNumber": "221112233"
}
> {%
    client.global.set("gym_id_1", response.body.id);
%}

### 2. Iron Gym
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Iron Gym",
  "address": "ul. Krakowska 5, 12-345 Kraków",
  "phoneNumber": "124445566"
}
> {%
    client.global.set("gym_id_2", response.body.id);
%}

### 3. FitLife Center
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "FitLife Center",
  "address": "ul. Świdnicka 1, Wrocław",
  "phoneNumber": "717778899"
}
> {%
    client.global.set("gym_id_3", response.body.id);
%}

### 4. Puławy Gym
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Pulawy Gym",
  "address": "ul. Lubelska 123, 24-100 Puławy",
  "phoneNumber": "+48611231231"
}
> {%
    client.global.set("gym_id_4", response.body.id);
%}

### 5. Super Gym
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Super Gym",
  "address": "ul. Długa 45/3, Lublin",
  "phoneNumber": "+48 123231231"
}
> {%
    client.global.set("gym_id_5", response.body.id);
%}

###  Get all gyms
GET {{baseUrl}}