### Variables
@baseUrl = http://localhost:8080/api

### 1. Plan 1 for Gym 1
POST {{baseUrl}}/gyms/{{gym_id_1}}/membership-plans
Content-Type: application/json

{
  "name": "Plan 1 Power House",
  "plan": "BASIC",
  "monthlyPrice": {
    "amount": 100.00,
    "currency": "PLN"
  },
  "durationInMonths": 1,
  "maxMembers": 100
}
> {% client.global.set("plan_id_1", response.body.id); %}

### 2. Plan 2 for Gym 1
POST {{baseUrl}}/gyms/{{gym_id_1}}/membership-plans
Content-Type: application/json

{
  "name": "Plan 2 Power House",
  "plan": "BASIC",
  "monthlyPrice": {
    "amount": 500.12,
    "currency": "PLN"
  },
  "durationInMonths": 6,
  "maxMembers": 150
}
> {% client.global.set("plan_id_2", response.body.id); %}

### 3. Plan 3 for Gym 1
POST {{baseUrl}}/gyms/{{gym_id_1}}/membership-plans
Content-Type: application/json

{
  "name": "Plan 3 Power House",
  "plan": "PREMIUM",
  "monthlyPrice": {
    "amount": 250.71,
    "currency": "EUR"
  },
  "durationInMonths": 12,
  "maxMembers": 50
}
> {% client.global.set("plan_id_3", response.body.id); %}

### 4. Plan 4 for Gym 4
POST {{baseUrl}}/gyms/{{gym_id_4}}/membership-plans
Content-Type: application/json

{
  "name": "Default 3 years",
  "plan": "BASIC",
  "monthlyPrice": {
    "amount": 89.00,
    "currency": "PLN"
  },
  "durationInMonths": 36,
  "maxMembers": 30
}
> {% client.global.set("plan_id_4", response.body.id); %}

### 5. Plan 5 for Gym 5
POST {{baseUrl}}/gyms/{{gym_id_5}}/membership-plans
Content-Type: application/json

{
  "name": "Super VIP Elite",
  "plan": "PREMIUM",
  "monthlyPrice": {
    "amount": 299.99,
    "currency": "GBP"
  },
  "durationInMonths": 1,
  "maxMembers": 1
}
> {% client.global.set("plan_id_5", response.body.id); %}

### Get plans for Gym 1
GET {{baseUrl}}/gyms/{{gym_id_1}}/membership-plans

### Get plans for Gym 4
GET {{baseUrl}}/gyms/{{gym_id_4}}/membership-plans

### Get plans for Gym 2
GET {{baseUrl}}/gyms/{{gym_id_2}}/membership-plans